# Constants for logs
LOG_TRANSFERENCE_RECEIVED_OK = 'TRANSFERENCE_RECEIVED_SUCCESSFUL'
LOG_TRANSFERENCE_SENT_OK = 'TRANSFERENCE_SENT_SUCCESSFUL'
LOG_TRANSFERENCE_SENT_ERROR = 'TRANSFERENCE_SENT_ERROR'
LOG_DEPOSIT_OK = 'DEPOSIT_SUCCESSFUL'
LOG_WITHDRAWAL_OK = 'WITHDRAWAL_SUCCESSFUL'
LOG_WITHDRAWAL_ERROR = 'WITHDRAWAL_ERROR'

LOG_TYPES = (
    (LOG_TRANSFERENCE_RECEIVED_OK, 'Successful transference received'),
    (LOG_TRANSFERENCE_SENT_OK, 'Successful transference sent'),
    (LOG_TRANSFERENCE_SENT_ERROR, 'Error in transference sent'),
    (LOG_DEPOSIT_OK, 'Successful deposit'),
    (LOG_WITHDRAWAL_OK, 'Successful withdrawal'),
    (LOG_WITHDRAWAL_ERROR, 'Error in withdrawal'),
)


# Constants for operations
OPERATION_TRANSFERENCE = 'TRANSFERENCE'
OPERATION_DEPOSIT = 'DEPOSIT'
OPERATION_WITHDRAWAL = 'WITHDRAWAL'

OPERATION_TYPES = (
    (OPERATION_TRANSFERENCE, 'Transference'),
    (OPERATION_DEPOSIT, 'Deposit'),
    (OPERATION_WITHDRAWAL, 'Withdrawal'),
)
