# Generated by Django 4.1.2 on 2022-10-18 22:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("currencies", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("amount", models.FloatField()),
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=100, unique=True
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals",
                        to="users.useraccount",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="currencies.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("amount", models.FloatField()),
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=100, unique=True
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="currencies.currency",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_transferences",
                        to="users.useraccount",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_transferences",
                        to="users.useraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("TRANSFERENCE", "Transference"),
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            (
                                "TRANSFERENCE_RECEIVED_SUCCESSFUL",
                                "Successful transference received",
                            ),
                            (
                                "TRANSFERENCE_SENT_SUCCESSFUL",
                                "Successful transference sent",
                            ),
                            ("TRANSFERENCE_SENT_ERROR", "Error in transference sent"),
                            ("DEPOSIT_SUCCESSFUL", "Successful deposit"),
                            ("WITHDRAWAL_SUCCESSFUL", "Successful withdrawal"),
                            ("WITHDRAWAL_ERROR", "Error in withdrawal"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=100, unique=True
                    ),
                ),
                ("additional_info", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="users.useraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("amount", models.FloatField()),
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=100, unique=True
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_deposits",
                        to="users.useraccount",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="currencies.currency",
                    ),
                ),
            ],
        ),
    ]
